// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mcalc
List mcalc(const int iT, const int ip, const int iq, const arma::mat& mX, const arma::mat& me, const arma::mat& Gam, const arma::mat& Bet, const arma::mat& mG, const arma::vec& h0, const arma::vec& mX0);
RcppExport SEXP _LinKF_mcalc(SEXP iTSEXP, SEXP ipSEXP, SEXP iqSEXP, SEXP mXSEXP, SEXP meSEXP, SEXP GamSEXP, SEXP BetSEXP, SEXP mGSEXP, SEXP h0SEXP, SEXP mX0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type iT(iTSEXP);
    Rcpp::traits::input_parameter< const int >::type ip(ipSEXP);
    Rcpp::traits::input_parameter< const int >::type iq(iqSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type me(meSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Gam(GamSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Bet(BetSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mG(mGSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type h0(h0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mX0(mX0SEXP);
    rcpp_result_gen = Rcpp::wrap(mcalc(iT, ip, iq, mX, me, Gam, Bet, mG, h0, mX0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LinKF_mcalc", (DL_FUNC) &_LinKF_mcalc, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_LinKF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
