# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcalc_sim <- function(iT, ip, iq, mX, me, Gam, Bet, mG, h0, mX0) {
    .Call(`_LinKF_mcalc_sim`, iT, ip, iq, mX, me, Gam, Bet, mG, h0, mX0)
}

mcalc_kf <- function(iT, ip, iq, mZ, mX, mF, mB, mH, mA, RR, QQ, h0, mX0, P0) {
    .Call(`_LinKF_mcalc_kf`, iT, ip, iq, mZ, mX, mF, mB, mH, mA, RR, QQ, h0, mX0, P0)
}

