# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcalc <- function(iT, ip, iq, mX, me, Gam, Bet, mG, h0, mX0) {
    .Call(`_LinKF_mcalc`, iT, ip, iq, mX, me, Gam, Bet, mG, h0, mX0)
}

